### ISSUE TITLE
hi,it seems the art is not mirrored now.

### ISSUE THREAD

**Issue by AndroidInternal** [aosp-mirror/art#1]
do you forget to mirror it?

**Comment by SpecialCyCi** [comment]
+1

**Comment by jan4984** [comment]
:+1

**Comment by mko-io** [comment]
+1

**Comment by Joyounger** [comment]
+1

**Comment by ireslabpragati** [comment]
The ART team does not manage the mirroring of the project directly. We have reported it to the owners, but there are no plans to fix this in the near term.

It would be quite difficult to build ART independently of other Android sources, so it'd be easier to use AOSP directly (as the ART team does itself).

There are instructions for downloading Android sources here:

  https://source.android.com/setup/build/downloading

And building here:

  https://source.android.com/setup/build/building

After you've set up a lunch target, you can build just ART with:

  $ cd $ANDROID_BUILD_TOP/art
  $ mma

If you want to run tests on host:

  $ cd $ANDROID_BUILD_TOP
  $ art/tools/buildbot.sh --host -j16
  $ art/test.py --host

Happy Hacking!

**Comment by erpragatisingh** [comment]
The ART team does not manage the mirroring of the project directly. We have reported it to the owners, but there are no plans to fix this in the near term.

It would be quite difficult to build ART independently of other Android sources, so it'd be easier to use AOSP directly (as the ART team does itself).

There are instructions for downloading Android sources here:

  https://source.android.com/setup/build/downloading

And building here:

  https://source.android.com/setup/build/building

After you've set up a lunch target, you can build just ART with:

  $ cd $ANDROID_BUILD_TOP/art
  $ mma

If you want to run tests on host:

  $ cd $ANDROID_BUILD_TOP
  $ art/tools/buildbot.sh --host -j16
  $ art/test.py --host

Happy Hacking!

**Comment by jbmagination** [comment]
I think this can be closed now...

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
